name=input('姓名:')
QQ=input('QQ:')
phone_number=input('手机号:')
school_adress=input('学校地址:')
print('='*50)
print('姓名:%s\n\nQQ:%s\n\n手机号:%s\n\n学校地址:%s\n\n'%(name,QQ,phone_number,school_adress))
print('='*50)
